### PR TITLE
don't break SSR

### PR DESCRIPTION
**Pull request by badtant**
https://github.com/theplatapi/react-disqus-thread/issues/4

### CODE REVIEW

**Comment by theplatapi** [comment]
Does the second reference to `window` [here](https://github.com/theplatapi/react-disqus-thread/pull/5/files#diff-00f057dda29e5838882914070baf42b4L95) break SSR?

**Comment by badtant** [comment]
no, that worked fine

**Comment by theplatapi** [comment]
Alright cool. The changes look good. Can you also commit an updated pre-compiled file? `npm run build` and commit the updated file.

**Comment by badtant** [comment]
yes, but not until monday :)

**Comment by badtant** [comment]
added

**Comment by badtant** [comment]
any time to merge and make a release?

**Comment by theplatapi** [comment]
Released

**Pull request merged**
